"use strict";var q=void 0,s=!1;var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},invalid:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},bug:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},notReady:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}}};
"undefined"!==typeof module&&module.exports&&(module.exports=sjcl);"function"===typeof define&&define([],function(){return sjcl});
sjcl.cipher.aes=function(a){this.i[0][0][0]||this.u();var b,c,d,e,g=this.i[0][4],f=this.i[1];b=a.length;var h=1;if(4!==b&&6!==b&&8!==b)throw new sjcl.exception.invalid("invalid aes key size");this.b=[d=a.slice(0),e=[]];for(a=b;a<4*b+28;a++){c=d[a-1];if(0===a%b||8===b&&4===a%b)c=g[c>>>24]<<24^g[c>>16&255]<<16^g[c>>8&255]<<8^g[c&255],0===a%b&&(c=c<<8^c>>>24^h<<24,h=h<<1^283*(h>>7));d[a]=d[a-b]^c}for(b=0;a;b++,a--)c=d[b&3?a:a-4],e[b]=4>=a||4>b?c:f[0][g[c>>>24]]^f[1][g[c>>16&255]]^f[2][g[c>>8&255]]^f[3][g[c&
255]]};
sjcl.cipher.aes.prototype={encrypt:function(a){return v(this,a,0)},decrypt:function(a){return v(this,a,1)},i:[[[],[],[],[],[]],[[],[],[],[],[]]],u:function(){var a=this.i[0],b=this.i[1],c=a[4],d=b[4],e,g,f,h=[],n=[],m,p,k,l;for(e=0;0x100>e;e++)n[(h[e]=e<<1^283*(e>>7))^e]=e;for(g=f=0;!c[g];g^=m||1,f=n[f]||1){k=f^f<<1^f<<2^f<<3^f<<4;k=k>>8^k&255^99;c[g]=k;d[k]=g;p=h[e=h[m=h[g]]];l=0x1010101*p^0x10001*e^0x101*m^0x1010100*g;p=0x101*h[k]^0x1010100*k;for(e=0;4>e;e++)a[e][g]=p=p<<24^p>>>8,b[e][k]=l=l<<24^l>>>8}for(e=
0;5>e;e++)a[e]=a[e].slice(0),b[e]=b[e].slice(0)}};
function v(a,b,c){if(4!==b.length)throw new sjcl.exception.invalid("invalid aes block size");var d=a.b[c],e=b[0]^d[0],g=b[c?3:1]^d[1],f=b[2]^d[2];b=b[c?1:3]^d[3];var h,n,m,p=d.length/4-2,k,l=4,u=[0,0,0,0];h=a.i[c];a=h[0];var r=h[1],t=h[2],x=h[3],y=h[4];for(k=0;k<p;k++)h=a[e>>>24]^r[g>>16&255]^t[f>>8&255]^x[b&255]^d[l],n=a[g>>>24]^r[f>>16&255]^t[b>>8&255]^x[e&255]^d[l+1],m=a[f>>>24]^r[b>>16&255]^t[e>>8&255]^x[g&255]^d[l+2],b=a[b>>>24]^r[e>>16&255]^t[g>>8&255]^x[f&255]^d[l+3],l+=4,e=h,g=n,f=m;for(k=
0;4>k;k++)u[c?3&-k:k]=y[e>>>24]<<24^y[g>>16&255]<<16^y[f>>8&255]<<8^y[b&255]^d[l++],h=e,e=g,g=f,f=b,b=h;return u}
sjcl.bitArray={bitSlice:function(a,b,c){a=sjcl.bitArray.D(a.slice(b/32),32-(b&31)).slice(1);return c===q?a:sjcl.bitArray.clamp(a,c-b)},extract:function(a,b,c){var d=Math.floor(-b-c&31);return((b+c-1^b)&-32?a[b/32|0]<<32-d^a[b/32+1|0]>>>d:a[b/32|0]>>>d)&(1<<c)-1},concat:function(a,b){if(0===a.length||0===b.length)return a.concat(b);var c=a[a.length-1],d=sjcl.bitArray.getPartial(c);return 32===d?a.concat(b):sjcl.bitArray.D(b,d,c|0,a.slice(0,a.length-1))},bitLength:function(a){var b=a.length;return 0===
b?0:32*(b-1)+sjcl.bitArray.getPartial(a[b-1])},clamp:function(a,b){if(32*a.length<b)return a;a=a.slice(0,Math.ceil(b/32));var c=a.length;b&=31;0<c&&b&&(a[c-1]=sjcl.bitArray.partial(b,a[c-1]&2147483648>>b-1,1));return a},partial:function(a,b,c){return 32===a?b:(c?b|0:b<<32-a)+0x10000000000*a},getPartial:function(a){return Math.round(a/0x10000000000)||32},equal:function(a,b){if(sjcl.bitArray.bitLength(a)!==sjcl.bitArray.bitLength(b))return s;var c=0,d;for(d=0;d<a.length;d++)c|=a[d]^b[d];return 0===
c},D:function(a,b,c,d){var e;e=0;for(d===q&&(d=[]);32<=b;b-=32)d.push(c),c=0;if(0===b)return d.concat(a);for(e=0;e<a.length;e++)d.push(c|a[e]>>>b),c=a[e]<<32-b;e=a.length?a[a.length-1]:0;a=sjcl.bitArray.getPartial(e);d.push(sjcl.bitArray.partial(b+a&31,32<b+a?c:d.pop(),1));return d},P:function(a,b){return[a[0]^b[0],a[1]^b[1],a[2]^b[2],a[3]^b[3]]},byteswapM:function(a){var b,c;for(b=0;b<a.length;++b)c=a[b],a[b]=c>>>24|c>>>8&0xff00|(c&0xff00)<<8|c<<24;return a}};
sjcl.codec.utf8String={fromBits:function(a){var b="",c=sjcl.bitArray.bitLength(a),d,e;for(d=0;d<c/8;d++)0===(d&3)&&(e=a[d/4]),b+=String.fromCharCode(e>>>24),e<<=8;return decodeURIComponent(escape(b))},toBits:function(a){a=unescape(encodeURIComponent(a));var b=[],c,d=0;for(c=0;c<a.length;c++)d=d<<8|a.charCodeAt(c),3===(c&3)&&(b.push(d),d=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),d));return b}};
sjcl.hash.sha256=function(a){this.b[0]||this.u();a?(this.m=a.m.slice(0),this.k=a.k.slice(0),this.f=a.f):this.reset()};sjcl.hash.sha256.hash=function(a){return(new sjcl.hash.sha256).update(a).finalize()};
sjcl.hash.sha256.prototype={blockSize:512,reset:function(){this.m=this.B.slice(0);this.k=[];this.f=0;return this},update:function(a){"string"===typeof a&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this.k=sjcl.bitArray.concat(this.k,a);b=this.f;a=this.f=b+sjcl.bitArray.bitLength(a);for(b=512+b&-512;b<=a;b+=512)w(this,c.splice(0,16));return this},finalize:function(){var a,b=this.k,c=this.m,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this.f/
4294967296));for(b.push(this.f|0);b.length;)w(this,b.splice(0,16));this.reset();return c},B:[],b:[],u:function(){function a(a){return 0x100000000*(a-Math.floor(a))|0}var b=0,c=2,d;a:for(;64>b;c++){for(d=2;d*d<=c;d++)if(0===c%d)continue a;8>b&&(this.B[b]=a(Math.pow(c,0.5)));this.b[b]=a(Math.pow(c,1/3));b++}}};
function w(a,b){var c,d,e,g=b.slice(0),f=a.m,h=a.b,n=f[0],m=f[1],p=f[2],k=f[3],l=f[4],u=f[5],r=f[6],t=f[7];for(c=0;64>c;c++)16>c?d=g[c]:(d=g[c+1&15],e=g[c+14&15],d=g[c&15]=(d>>>7^d>>>18^d>>>3^d<<25^d<<14)+(e>>>17^e>>>19^e>>>10^e<<15^e<<13)+g[c&15]+g[c+9&15]|0),d=d+t+(l>>>6^l>>>11^l>>>25^l<<26^l<<21^l<<7)+(r^l&(u^r))+h[c],t=r,r=u,u=l,l=k+d|0,k=p,p=m,m=n,n=d+(m&p^k&(m^p))+(m>>>2^m>>>13^m>>>22^m<<30^m<<19^m<<10)|0;f[0]=f[0]+n|0;f[1]=f[1]+m|0;f[2]=f[2]+p|0;f[3]=f[3]+k|0;f[4]=f[4]+l|0;f[5]=f[5]+u|0;f[6]=
f[6]+r|0;f[7]=f[7]+t|0}sjcl.prng=function(a){this.c=[new sjcl.hash.sha256];this.g=[0];this.v=0;this.n={};this.t=0;this.A={};this.C=this.d=this.h=this.K=0;this.b=[0,0,0,0,0,0,0,0];this.e=[0,0,0,0];this.r=q;this.s=a;this.l=s;this.q={progress:{},seeded:{}};this.j=this.J=0;this.o=1;this.p=2;this.G=0x10000;this.w=[0,48,64,96,128,192,0x100,384,512,768,1024];this.H=3E4;this.F=80};
sjcl.prng.prototype={randomWords:function(a,b){var c=[],d;d=this.isReady(b);var e;if(d===this.j)throw new sjcl.exception.notReady("generator isn't seeded");if(d&this.p){d=!(d&this.o);e=[];var g=0,f;this.C=e[0]=(new Date).valueOf()+this.H;for(f=0;16>f;f++)e.push(0x100000000*Math.random()|0);for(f=0;f<this.c.length&&!(e=e.concat(this.c[f].finalize()),g+=this.g[f],this.g[f]=0,!d&&this.v&1<<f);f++);this.v>=1<<this.c.length&&(this.c.push(new sjcl.hash.sha256),this.g.push(0));this.d-=g;g>this.h&&(this.h=
g);this.v++;this.b=sjcl.hash.sha256.hash(this.b.concat(e));this.r=new sjcl.cipher.aes(this.b);for(d=0;4>d&&!(this.e[d]=this.e[d]+1|0,this.e[d]);d++);}for(d=0;d<a;d+=4)0===(d+1)%this.G&&z(this),e=A(this),c.push(e[0],e[1],e[2],e[3]);z(this);return c.slice(0,a)},setDefaultParanoia:function(a,b){if(0===a&&"Setting paranoia=0 will ruin your security; use it only for testing"!==b)throw"Setting paranoia=0 will ruin your security; use it only for testing";this.s=a},addEntropy:function(a,b,c){c=c||"user";
var d,e,g=(new Date).valueOf(),f=this.n[c],h=this.isReady(),n=0;d=this.A[c];d===q&&(d=this.A[c]=this.K++);f===q&&(f=this.n[c]=0);this.n[c]=(this.n[c]+1)%this.c.length;switch(typeof a){case "number":b===q&&(b=1);this.c[f].update([d,this.t++,1,b,g,1,a|0]);break;case "object":c=Object.prototype.toString.call(a);if("[object Uint32Array]"===c){e=[];for(c=0;c<a.length;c++)e.push(a[c]);a=e}else{"[object Array]"!==c&&(n=1);for(c=0;c<a.length&&!n;c++)"number"!==typeof a[c]&&(n=1)}if(!n){if(b===q)for(c=b=0;c<
a.length;c++)for(e=a[c];0<e;)b++,e>>>=1;this.c[f].update([d,this.t++,2,b,g,a.length].concat(a))}break;case "string":b===q&&(b=a.length);this.c[f].update([d,this.t++,3,b,g,a.length]);this.c[f].update(a);break;default:n=1}if(n)throw new sjcl.exception.bug("random: addEntropy only supports number, array of numbers or string");this.g[f]+=b;this.d+=b;h===this.j&&(this.isReady()!==this.j&&B("seeded",Math.max(this.h,this.d)),B("progress",this.getProgress()))},isReady:function(a){a=this.w[a!==q?a:this.s];
return this.h&&this.h>=a?this.g[0]>this.F&&(new Date).valueOf()>this.C?this.p|this.o:this.o:this.d>=a?this.p|this.j:this.j},getProgress:function(a){a=this.w[a?a:this.s];return this.h>=a?1:this.d>a?1:this.d/a},startCollectors:function(){if(!this.l){this.a={loadTimeCollector:C(this,this.M),mouseCollector:C(this,this.N),keyboardCollector:C(this,this.L),accelerometerCollector:C(this,this.I),touchCollector:C(this,this.O)};if(window.addEventListener)window.addEventListener("load",this.a.loadTimeCollector,
s),window.addEventListener("mousemove",this.a.mouseCollector,s),window.addEventListener("keypress",this.a.keyboardCollector,s),window.addEventListener("devicemotion",this.a.accelerometerCollector,s),window.addEventListener("touchmove",this.a.touchCollector,s);else if(document.attachEvent)document.attachEvent("onload",this.a.loadTimeCollector),document.attachEvent("onmousemove",this.a.mouseCollector),document.attachEvent("keypress",this.a.keyboardCollector);else throw new sjcl.exception.bug("can't attach event");
this.l=!0}},stopCollectors:function(){this.l&&(window.removeEventListener?(window.removeEventListener("load",this.a.loadTimeCollector,s),window.removeEventListener("mousemove",this.a.mouseCollector,s),window.removeEventListener("keypress",this.a.keyboardCollector,s),window.removeEventListener("devicemotion",this.a.accelerometerCollector,s),window.removeEventListener("touchmove",this.a.touchCollector,s)):document.detachEvent&&(document.detachEvent("onload",this.a.loadTimeCollector),document.detachEvent("onmousemove",
this.a.mouseCollector),document.detachEvent("keypress",this.a.keyboardCollector)),this.l=s)},addEventListener:function(a,b){this.q[a][this.J++]=b},removeEventListener:function(a,b){var c,d,e=this.q[a],g=[];for(d in e)e.hasOwnProperty(d)&&e[d]===b&&g.push(d);for(c=0;c<g.length;c++)d=g[c],delete e[d]},L:function(){D(1)},N:function(a){var b,c;try{b=a.x||a.clientX||a.offsetX||0,c=a.y||a.clientY||a.offsetY||0}catch(d){c=b=0}0!=b&&0!=c&&sjcl.random.addEntropy([b,c],2,"mouse");D(0)},O:function(a){a=a.touches[0]||
a.changedTouches[0];sjcl.random.addEntropy([a.pageX||a.clientX,a.pageY||a.clientY],1,"touch");D(0)},M:function(){D(2)},I:function(a){a=a.accelerationIncludingGravity.x||a.accelerationIncludingGravity.y||a.accelerationIncludingGravity.z;if(window.orientation){var b=window.orientation;"number"===typeof b&&sjcl.random.addEntropy(b,1,"accelerometer")}a&&sjcl.random.addEntropy(a,2,"accelerometer");D(0)}};
function B(a,b){var c,d=sjcl.random.q[a],e=[];for(c in d)d.hasOwnProperty(c)&&e.push(d[c]);for(c=0;c<e.length;c++)e[c](b)}function D(a){"undefined"!==typeof window&&window.performance&&"function"===typeof window.performance.now?sjcl.random.addEntropy(window.performance.now(),a,"loadtime"):sjcl.random.addEntropy((new Date).valueOf(),a,"loadtime")}function z(a){a.b=A(a).concat(A(a));a.r=new sjcl.cipher.aes(a.b)}
function A(a){for(var b=0;4>b&&!(a.e[b]=a.e[b]+1|0,a.e[b]);b++);return a.r.encrypt(a.e)}function C(a,b){return function(){b.apply(a,arguments)}}sjcl.random=new sjcl.prng(6);
a:try{var E,F,G,H;if(H="undefined"!==typeof module){var I;if(I=module.exports){var J;try{J=require("crypto")}catch(K){J=null}I=(F=J)&&F.randomBytes}H=I}if(H)E=F.randomBytes(128),E=new Uint32Array((new Uint8Array(E)).buffer),sjcl.random.addEntropy(E,1024,"crypto['randomBytes']");else if("undefined"!==typeof window&&"undefined"!==typeof Uint32Array){G=new Uint32Array(32);if(window.crypto&&window.crypto.getRandomValues)window.crypto.getRandomValues(G);else if(window.msCrypto&&window.msCrypto.getRandomValues)window.msCrypto.getRandomValues(G);
else break a;sjcl.random.addEntropy(G,1024,"crypto['getRandomValues']")}}catch(L){"undefined"!==typeof window&&window.console&&(console.log("There was an error collecting entropy from the browser:"),console.log(L))};
