"use strict"

const verbs = []
const adjectives = []
const nouns = []
const alternateVAN = [[],[],[]]

verbs[3]='AteDugFedGotHetHidLedRanSat'
verbs[4]='ActsAgedAimsArmsAsksBadeBansBegsBentBetsBledBlewBornCameCutsDipsDoveDrewDrugDrysDubsEndsFellFeltFitsFixsFlewGaveGoesGrewHeldHitsHungKeptLentLogsLostMadeMapsMoltNodsOptsOwnsPinsPledPopsPutsRidsRipsRobsRodeRoseRubsSangSankSetsSkisSlidSpanSpedSwamTagsTapsTextTipsToldTookTopsUsedUsesVowsWokeWove'
verbs[5]='AroseBacksBakedBeganBillsBindsBlestBoilsBooksBurnsCalmsCampsCaredChoseClangCooksCoolsCostsCriedCuredDaredDatedDrankDrestDropsDroveDumpsEchosEditsExitsFacedFadedFailsFarmsFillsFilmsFindsFinedFiredFoldsFormsFoundFreedFriedFuelsFundsGainsGazedGrabsGrinsHaltsHandsHarmsHeadsHelpsHintsHiredHooksHostsHuntsHurtsIronsJailsJoinsJokedJumpsKicksLandsLastsLeapsLiftsLikedLinedLinksListsLivedLooksLoomsLovedMatedMightMindsMixedMovedMustsNamedNotedNumbsObeysOpensPacedParksPiledPlansPlaysPlotsPlugsPosedPostsPullsPumpsQuitsQuothRaidsRatedRentsRisksRollsRuinsRuledSavedScansSeatsShedsShipsShoneShookShopsShutsSkipsSlamsSlapsSleptSlipsSmeltSnapsSnowsSortsSpeltSpentSpiedSpiltSpokeSpotsStabsStaidStarsStemsStirsStoodStopsStuckStunsSwangSweptSworeTalksTaxedTendsTermsTestsTimedToursTrapsTriedTripsTypedUrgedViewsVotedWalksWantsWarmsWarnsWhipsWipedWorksYells'
verbs[6]='AbusedAdaptsAdmitsAdoptsAgreedAlarmsAlertsAlignsAllowsAmendsAnnoysArguedAvoidsAwaitsAwardsBankedBecameBlamedBlastsBoardsBoastsBoostsBrandsBringsBuriedBurstsCannotCarvedCatersCeasedChainsChartsChasedCheatsCheersClaimsCleansClearsCoachsCopiedCracksCrashsCurvedCycledDancedDefiedDelaysDeniedDoubtsDrainsDreamsDriftsDrownsElectsEmailsEmbedsEnactsEnjoysEnrolsEnsuedEntersEqualsEquipsErectsEruptsEvokedExertsExistsFavorsFightsFloatsFloodsForbadForcedForgedForgotFramedGradedGrantsGraspsGreetsGrindsGuardsGuidedHauntsHonorsHousedIncursInfersIssuedJudgedKissedLabelsLaughsLearnsLevelsLimitsMergedMessedMissedModelsMountsOccursOffersOrdersPaintsPassedPausedPlantsPointsPowersPricedPrintsProbedProvedPushedReactsRefersReliedRenewsReplysRushedScapedScaredScoredScrewsSeizedServedShallsShapedSharedShiftsShocksShoutsShrankShrugsSlicedSlopedSmiledSmokedSoundsSparedSparksSplitsSpoilsSprangStagedStartsStatedSteersStoredStroveStruckStuffsTastedTaughtTemptsThanksThinksThroveTitledTossedTotalsTracedTracksTradedTrailsTrainsTreatsTricksTrustsTwistsUnitedUpheldUpsetsValuedVisitsWashedWatersWidensWoundsYields'

adjectives[2]='Ok'
adjectives[3]='BadBigDryFarFatFewFitHotMadNetOddOldOwnPopSadShyTenTopToy'
adjectives[4]='AcidAgedBackBentBestBlueBoldBusyCalmColdCoolCultCuteDarkDeadDeepDullDumbEastEasyEvenEvilFastFineFirmFiveFlatFolkFreeFullGladGoldGoodGreyHardHugeHurtKeenKindLateLazyLeftLiveLongLostLoudMassMildNearNeatNextNineOnlyOpenOralPastPinkPlusPureRareRearRichSafeSameShutSoftSoloSureTallTeenThinTidyTinyTrueTwinUglyUsedVastWarmWestWideWildWiseZero'
adjectives[5]='AcuteAdultAlertAlienAlikeAliveAloneAngryArmedAudioAwareBasedBasicBlackBlankBlindBlondBoredBoundBraveBriefBroadBrownChiefCivicCivilCleanClearComicCrazyCreamCurlyDailyDairyDenseDirtyDrunkEagerEarlyEmptyEqualExactExtraFalseFancyFiftyFinalFixedFreshFrontFunnyGiantGrandGraveGreenGrossHandyHappyHarshHeavyHumanIdealInnerJointLargeLegalLevelLightLocalLooseLoyalMagicMajorMinorMixedMoralMotorNakedNastyNobleNoisyNorthNovelOtherOuterPrimeProudQuietRapidReadyRiskyRivalRoundRuralScarySharpShinyShortSillySixtySmallSmartSolarSolidSorrySoundSouthSpareSpicyStarkStateSteepStiffStillSuperThickThreeTightTiredTotalToxicUpperUpsetUrbanUsualVagueValidVitalVocalWeirdWorseWorthWrongYoung'
adjectives[6]='AbsentAbsurdActiveActualAfraidAmazedAnnualAsleepBetterBitterBoringBottomBrightBrokenBrutalCasualCleverClosedCommonCostlyCurvedDecentDirectDivineDoubleEightyElevenEntireEthnicExcessExoticExpertFailedFamilyFamousFemaleFierceFiscalFlawedFlyingFormalFormerFrozenFutureGentleGlobalGoogolGuiltyHiddenHollowHonestHumbleHungryImmuneIndoorInsideIntactIronicJuniorLatterLesserLethalLiableLikelyLinearLiquidLittleLivingLonelyLovelyMatureMediumMentalMiddleMinuteMobileModernModestMovingMutualNarrowNativeNormalOnlineOrangePolitePrettyProperPublicPurpleRacialRacistRandomRecentRemoteRobustRubberSacredScaredSecureSeniorSevereShapedSilentSilverSimpleSingleSmoothSocialSpokenStableSteadyStickyStrictStrongStupidSuddenThirtyTimelyTragicTribalTwelveTwentyUnableUnfairUniqueUnitedUrgentUsefulVariedVerbalViableVisualWoodenYellow'

nouns[3]='CDsTVs'
nouns[4]='ActsAgesAidsAimsAppsArmsArtsBagsBansBedsBetsBidsBinsBugsCapsCarsCatsCopsCupsCutsDadsDataDotsDuosDVDsEggsEgosEndsErasFansFatsFeesFitsGapsGigsGoesGunsGutsGuysGymsHatsHipsHitsIcesInksJetsJobsJoysKidsKitsLabsLadsLegsLipsLogsMansMapsMaysMobsMudsNetsNewsNextNutsOddsOilsPadsPensPetsPinsPitsPopsPubsRodsRunsSetsSirsSkisTagsTapsTinsTipsTopsToysUsesVansWarsWebs'
nouns[5]='AcidsAcresAreasAshesAutosBacksBandsBanksBathsBeamsBeansBeefsBeltsBendsBestsBikesBillsBirdsBlogsBlowsBluesBoatsBondsBonesBooksBoomsBootsBoxesBucksBulksBurnsCafesCakesCalmsCampsCardsCaresCasesCavesChefsChipsClipsClubsCluesCodesColdsCooksCornsCostsCrewsCriesCropsCultsCuresDarksDatesDebtsDecksDeedsDesksDietsDirtsDiscsDisksDivesDoorsDosesDropsDrugsDrumsEastsEchosEdgesEurosEvilsExamsExitsFacesFactsFallsFamesFarmsFatesFeatsFeedsFeelsFilmsFinesFiresFirmsFixesFlagsFlatsFlawsFliesFoldsFolksFoodsFoolsFootsForksFormsFuelsFundsGainsGamesGasesGazesGearsGiftsGirlsGoalsGoldsGolfsGoodsGreysGridsGrinsHaltsHandsHarmsHeadsHeatsHelpsHerbsHillsHintsHiresHoldsHooksHornsHostsHuntsHurtsIconsIdeasInfosIronsItemsJailsJokesJumpsJunesKicksKindsKingsKneesLakesLampsLandsLanesLastsLawnsLeadsLeapsLeftsLiftsLinesLinksLionsListsLogosLooksLordsLovesLucksLungsMakesMasksMatesMathsMealsMemosMenusMilesMindsMinesMixesModesMonksMoodsMoonsMovesMythsNailsNamesNecksNestsNoonsNormsNosesNotesOvensPacesPagesPalmsParksPartsPastsPathsPilesPillsPinksPipesPlansPlaysPleasPlotsPlugsPoemsPoetsPondsPostsPullsPumpsPunksRagesRaidsRailsRanksRatesRearsRentsRicesRidesRiotsRisesRisksRoadsRolesRollsRoofsRopesRosesRuinsRulesSakesSaltsSandsSeatsSelfsShipsShopsSidesSilksSizesSkiesSkinsSlotsSnowsSoapsSocksSoilsSolosSongsSortsSoupsSpamsSpansSpiesSpinsSpotsStarsStaysStemsStopsSwimsTalksTanksTapesTasksTaxesTaxisTeensTentsTermsTestsTextsTidesTimesToursTownsTrapsTreesTriesTriosTripsTubesTwinsTypesTyresUnitsUsersViewsVisasVotesWagesWalksWallsWardsWeedsWestsWingsWiresWivesWolfsWoolsWordsWorksYardsYearsZones'

for (let i = 3; i < 7; i++) {
  for (let j = 0; j < verbs[i].length; j += i) {
    alternateVAN[0].push(verbs[i].substring(j, j + i))
  }
}

for (let i = 2; i < 7; i++) {
  for (let j = 0; j < adjectives[i].length; j += i) {
    alternateVAN[1].push(adjectives[i].substring(j, j + i))
  }
}

for (let i = 3; i < 6; i++) {
  for (let j = 0; j < nouns[i].length; j += i) {
    alternateVAN[2].push(nouns[i].substring(j, j + i))
  }
}
